# Generated by Django 4.1.1 on 2022-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=200, verbose_name='Задание')),
                ('status', models.CharField(default='New', max_length=15, verbose_name='Статус')),
                ('deadline', models.DateField(default=None, verbose_name='Дата выполнения')),
            ],
        ),
    ]
