# Generated by Django 4.1.1 on 2022-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('process', 'В процессе'), ('done', 'Завершено')], default='New', max_length=15, verbose_name='Статус'),
        ),
    ]
